rscript: "Rscript"

ncells: 10000
ntry: 30
nbatch: 300

samples:
  - untreated
  - scramble
  - NCAPD2
  - NCAPD3
  - SMC2
  - WAPL24
  - WAPL48
  - MK1775
  - MK1775_ICRF193
  - RAD21
  - TT103
  - TT108

boot_samples:
  - untreated
  - scramble
  - NCAPD2
  - NCAPD3
  - SMC2
  - WAPL48
  - RAD21
  - TT108


